### ISSUE TITLE
Homey energy

### ISSUE THREAD

**Issue by Roylegr** [burnacid/homey-com.burnacid.ztatz#17]
In homey energy komen 2 waardes te staan 1 P1 generation en zonnepanelen. Van beide wordt gezegd dat ze leveren, maar eigenlijk levert P1 generation aan het net en de zonnepanelen aan het huis en/of het net. Dus zou P1 generation minus energy consumptie zijn. kan dit geïmplementeerd worden?

Homey energy shows 2 values, 1 P1 generation and solar panels.  Both are said to deliver, but P1 actually delivers generation to the grid and the solar panels to the house and / or grid.  So P1 generation would be minus energy consumption.  can this be implemented?

**Comment by burnacid** [comment]
Dit is hoe de Homey App werkt. Ik kan daar niets aan veranderen. Hij toont de totale energy die er geteld wordt.

**Comment by burnacid** [comment]
See also previous report #14
