### ISSUE TITLE
Day usage for Energie/Gas/Water[QUE]

### ISSUE THREAD

**Issue by AlfredG92** [burnacid/homey-com.burnacid.ztatz#18]
Allereerst dank voor de integratie tussen Ztatz P1 Monitor en Homey.
Ik heb de Ztatz toegevoegd in Homey, alleen als ik de verbruik van Energie en Gas aanklik zie ik het actuele verbruik, en de 3 meterstanden, Energie Piek en Dal en Gas en daarna of het Piek of Dal tarief is. Is het mogelijk dat hier het dagverbruik van Energie en Gas word toegevoegd? Ik ben een ex Homewizard Energylink gebruiken en hierin had je deze mogelijk die ik gebruikte wel.

Ben van plan om vanavond de watermeter aan de Ztatz toe te gaan voegen, weet niet of bij die optie ook een dagverbruik word gebruikt, anders zou dit ook een vraag zijn.

Alvast bedankt voor de genomen moeite.

**Comment by FalkeMichel** [comment]
Ik heb een PR klaar gezet voor de energie kant. Gas zit hier nog niet in, maar kan nog wel worden toegevoegd.

**Comment by AlfredG92** [comment]
Ok, Klinkt goed! Ben niet zo heel erg thuis in dit verhaal, maar zodra dit geupdate is in Homey app zou het zichtbaar moeten zijn? Als het werkt zou ik het erg op prijs stellen als je het Gas gedeelte ook nog zou kunnen toevoegen. Ik wacht de update af en laat het weten. Nogmaals dank voor de genomen moeite.

**Comment by AlfredG92** [comment]
Top, dankjewel! We gaan het afwachten, Wie moet zoiets accepteren?

**Comment by burnacid** [comment]
Zal kijken of de PR kan bekijken deze week. Dank voor je contributie

**Comment by burnacid** [comment]
Beta test naar de store gepushed. Kan je deze installeren en testen?

https://homey.app/nl-nl/app/com.burnacid.ztatz/ZTATZ/test/

**Comment by FalkeMichel** [comment]
Werkt hier prima! :)

**Comment by AlfredG92** [comment]
Werkt hier ook prima. Is het ook mogelijk om het water erbij te meubelen? Alvast dank naar iedereen die er aan meewerkt!

**Comment by burnacid** [comment]
Heb een nieuwe test versie klaar gezet met water dagelijks gebruik.
https://homey.app/a/com.burnacid.ztatz/test/

**Comment by AlfredG92** [comment]
Het ziet er goed uit, alleen 14 liter verbruik laat hij zien al 14m3 verbruik (14000L) dit moet dus nog even anders 😉😜

**Comment by burnacid** [comment]
Kan je mij de output van jou API sturen dan kan ik met die data even kijken

http://urlnaarZTATZ/api/v1/watermeter/day?json=object&limit=1

**Comment by AlfredG92** [comment]
[{"TIMESTAMP_UTC": 1588370400, "TIMESTAMP_lOCAL": "2020-05-02 00:00:00", "WATERMETER_CONSUMPTION_LITER": 15.0, "WATERMETER_CONSUMPTION_TOTAL_M3": 1077.369, "WATERMETER_PULS_COUNT": 15.0}]

**Comment by burnacid** [comment]
Als het goed is moet het zo wel kloppen: https://homey.app/nl-nl/app/com.burnacid.ztatz/ZTATZ/test/

**Comment by AlfredG92** [comment]
Ja, perfect. Mijn dank is groot!

**Comment by burnacid** [comment]
Versie 0.3.3 is live
