### ISSUE TITLE
[BUG] Cannot add my p1 ZTAZ device on my homey

### ISSUE THREAD

**Issue by DSGuess** [burnacid/homey-com.burnacid.ztatz#30]
After installing the app, I would like to add the energy monitor information to Homey, however when adding the P1 Usage tile I receive an error message: Socket.on is not a function

**To Reproduce**
1. Go to 'Homey app and add a device'
2. Click on 'ZTAZ app'
3. Select the 'P1 Usage tile'
4. Click the green connect button
5. It shows quickly a white screen add p1 usage
4. The following error shows: Socket.on is not a function
5. It returns to the choose the device you'd like to add to homey. 

**Expected behavior**
That the app is asking for the IP address of the energy monitor to be added. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Raspberry Pi - ZTAZ P1 Energie monitor
 - Homey Version: 5.0.1
 - App Version 0.50

**Comment by burnacid** [comment]
Seen. Artifact of the latest version sorry. Will try to fix this as soon as possible

**Comment by DSGuess** [comment]
Thanks! I'm available to test :-)

**Comment by burnacid** [comment]
Can you please go here and install this beta version: https://homey.app/a/com.burnacid.ztatz/test/

**Comment by DSGuess** [comment]
Great it works like a charm! Just tested it and I can confirm I can add the P1 usage device already.
