### ISSUE TITLE
[BUG] p1 daily usage 

### ISSUE THREAD

**Issue by locksen-nl** [burnacid/homey-com.burnacid.ztatz#35]
Bij Dailyusage krijg ik nu de fout, Apparaat niet beschikbaar 
Cannot read property 
WATERMETER_CONSUMPTION_LITER of
**Screenshots**
![image](https://user-images.githubusercontent.com/69047124/111067279-d6132480-84c3-11eb-9168-975fee3da145.jpeg)

![image](https://user-images.githubusercontent.com/69047124/111067285-dc090580-84c3-11eb-88c1-eeb6ca1ec1fe.jpeg)
**Smartphone (please complete the following information):**
 - Homey Version: 5.01
 - App Version 0.52 

Laatste versie p1monitor van maart

**Comment by burnacid** [comment]
Deze bug is gister opgelost met versie 0.5.2
Als het goed is moet hij automatisch installeren

**Comment by burnacid** [comment]
Gebruik je waterconsumptie in ZTATZ?

**Comment by locksen-nl** [comment]
> Gebruik je waterconsumptie in ZTATZ?

Nee

**Comment by burnacid** [comment]
Kan je eens een export van je API sturen

http://_urlnaarjouZTATZ_/api/v1/watermeter/day?json=object&limit=1

**Comment by locksen-nl** [comment]
> Kan je eens een export van je API sturen
> 
> 
> 
> http://_urlnaarjouZTATZ_/api/v1/watermeter/day?json=object&limit=1

{"title": "404 Not Found"}

**Comment by burnacid** [comment]
Mmm dat komt waarschijnlijk omdat de maker van ZTATZ heeft gemeld dat er een bug zit voor wie water comsumption gebruikt. Helaas heb ik daarom die van mij niet op de laatste versie draaien om te checken wat er exact anders is.

Schijnbaar is de API link dus veranderd. Ik ga even kijken of ik daar iets mee kan.

**Comment by locksen-nl** [comment]
> Mmm dat komt waarschijnlijk omdat de maker van ZTATZ heeft gemeld dat er een bug zit voor wie water comsumption gebruikt. Helaas heb ik daarom die van mij niet op de laatste versie draaien om te checken wat er exact anders is.
> 
> 
> 
> Schijnbaar is de API link dus veranderd. Ik ga even kijken of ik daar iets mee kan.

Bij de laatste versie is de bug over de water meting opgelost

**Comment by burnacid** [comment]
Dan ga ik die eens even updaten. Wellicht zijn er meedere zaken veranderd.
Heb ergens gelezen dat er een v2 van de API kwam

**Comment by locksen-nl** [comment]
> Dan ga ik die eens even updaten. Wellicht zijn er meedere zaken veranderd.
> 
> Heb ergens gelezen dat er een v2 van de API kwam

Water meter is nu api v2

![image](https://user-images.githubusercontent.com/69047124/111067999-20e26b80-84c7-11eb-9936-21b7aa72d099.jpeg)

**Comment by burnacid** [comment]
Mijn RPI is aan het updaten. Maar dat duurt altijd wel even. Kan je me de inhoud van watermeter/day/help even hier posten?
Wellicht is het enkel een kleine aanpassing.

**Comment by locksen-nl** [comment]
{
  "api_description": "Historical watermeter data.",
  "api_options": "limit {default all, >0 } number of entries returned, sort (on timestamp) {default desc, asc} sort on timestamp, json {default array, object} json output options see https://www.json.org/, round {default off, on} round to the nearest integer, no fractions in the output, starttime {default now, YYYY-MM-DD HH:MM:SS} from which moment in time data should retrieved, range {YYYY-MM-DD HH:MM:SS} all records that fit the timestamp string will be retrieved",
  "api_status": "test",
  "api_usage": "<ip>{/api/v2/watermeter/minute, /api/v2/watermeter/hour, /api/v2/watermeter/day, /api/v2/watermeter/month, /api/v2/watermeter/year}?limit=10&sort=asc&json=object&round=on&starttime=2019-11-30 12:03:55, or range=2020-01-03, <ip>{/api/v2/watermeter/hour, /api/v2/watermeter/day, /api/v2/watermeter/month, /api/v2/watermeter/year},<ip>{/api/v2/watermeter/hour/help, /api/v2/watermeter/day/help, /api/v2/watermeter/month/help, /api/v2/watermeter/month/help}",
  "api_version": 1,
  "fields": [
    {
      "description": "Time in format yyyy-mm-dd hh:mm:ss",
      "name": "TIMESTAMP_lOCAL",
      "type": "string"
    },
    {
      "description": "UTC timestamp",
      "name": "TIMESTAMP_UTC",
      "type": "integer"
    },
    {
      "description": "Number/index of time period 11-15 (minute,day,hour,month,year).",
      "name": "TIMEPERIOD_ID",
      "type": "integer"
    },
    {
      "description": "Nummer of detected pulses per timeunit (minute,hour, day, month, year).",
      "name": "WATERMETER_PULS_COUNT",
      "type": "integer"
    },
    {
      "description": "Liter of waterused per timeunit (minute,hour, day, month, year).",
      "name": "WATERMETER_CONSUMPTION_LITER",
      "type": "number"
    },
    {
      "description": "Consumption of water in M3 during the period.",
      "name": "WATERMETER_CONSUMPTION_TOTAL_M3",
      "type": "number"
    }
  ]
}

**Comment by burnacid** [comment]
Moet even gaan bedenken hoe ik dit goed ga opvangen zodat ook oude versies van ZTATZ blijven werken.
Probeer dit z.s.m. opgelost te krijgen. Dank voor de melding

**Comment by locksen-nl** [comment]
heb mijne nu tijdelijk gefixt door de water meter er uit te halen

**Comment by burnacid** [comment]
Zou je willen testen met deze versie: https://homey.app/a/com.burnacid.ztatz/test/

**Comment by locksen-nl** [comment]
> Zou je willen testen met deze versie: https://homey.app/a/com.burnacid.ztatz/test/

Het werkt
