### ISSUE TITLE
Cannot add sensor anymore

### ISSUE THREAD

**Issue by DSGuess** [burnacid/homey-com.burnacid.ztatz#38]
I have been running the homey component for some time. However it started showing a red exclamation every few hours. 
So I tried to remove the devices, and tried to add them again.  That did not work anymore. 

When I now add for example the p1 usage sensor:

It shows the screen with follow the instructions to add the URL:
So I add the IP from my unit: http://192.*.*.*

After adding the IP it shows the message:

No new devices have been found. 

So I checked if there was a newer version op de P1 ZTATZ software and there was. So I updated the Raspberry.
Rebooted my Homey, and re-added the app several times. However this does not change the situation.  

Is there anything I can try to resolve this?

**Comment by burnacid** [comment]
What version of the app are you running?
What version of homey are you running?

Please do the following.

Restart the ZTATZ app
Then try and add a device again
When that fails go in to the ZTATZ app in homey. And click create diagnostic report. Then I'll receive some debug info to see if I can seen an issue

**Comment by DSGuess** [comment]
Wow! Superfast response! I am running version V0.5.3 

And I have done the requested steps, Unfortunately the same error occurs. 
The following code has been generated with the diagnostics function: c4631981-6889-4000-82b2-14aa971ff221

**Comment by burnacid** [comment]
---- stdout ----
2021-04-19 14:51:06 [log] [ztatzP1Mon] ztatzP1Mon is running...
2021-04-19 14:51:38 [log] [ManagerDrivers] [ztatz_p1_Usage] _onPairSearchDevices
2021-04-19 14:51:38 [log] [ManagerDrivers] [ztatz_p1_Usage] _onPairListDevices
2021-04-19 14:51:38 [log] [ManagerDrivers] [ztatz_p1_Usage] []

---- stderr ----

**Comment by burnacid** [comment]
Please confirm to me the following

Is the old Ztatz usage sensor remove from your homey?
You can't add it twice.

Please open your ZTATZ dashboard
Go to the settings page
Open API in the left menu
In here you will see all API call URL's for example

192.168.1.100/api/v1/catalog

Please make sure when adding a sensor in home you use the correct address.
For the example that should be http://192.168.1.100
So please add http:// to the url and remove the /api/v1/catalog from the url

If that doesn't help than I'll need to create extended logging in the app so I can debug what is going on

**Comment by DSGuess** [comment]
Actually I uninstalled the app, and there are no sensors showing at the moment. So it looks like the sensors were not deleted. However they also do not show up at the moment. 

The URL I added was http://192.168.1.100 (using my own ip :-) )

**Comment by DSGuess** [comment]
Strange but true... Now it works again. Adding the sensors to my Homey. 
It feels like there is a delayed cleanup process or something.
