### ISSUE TITLE
[REQ] Add Solar API 

### ISSUE THREAD

**Issue by graafas** [burnacid/homey-com.burnacid.ztatz#41]
Hi,

could you consider to add the Solar API inside the App

**Comment by burnacid** [comment]
Why not directly use the app for SolarEdge? 
https://homey.app/en-ca/app/solaredge.modbus/SolarEdge/

**Comment by graafas** [comment]
ok thanks, I didn't know that. Before I uses the app zonnepanelen. This app uses the API and because the P1mon ZTATZ uses this also . So the APi was called to much. I wil look for this sugestion, thanks.
