### ISSUE TITLE
[BUG] Ztatz connection fails after a few minutes

### ISSUE THREAD

**Issue by Cuflee** [burnacid/homey-com.burnacid.ztatz#42]
**Describe the bug**
Installed ZTATZ and added the "P1 Dagelijks verbruik" device for the local URL http://p1mon.fritz.box. Pressed "check" and it found the "P1 Daily Usage" after that it added and was indicating usage flawlessly. I've also added "P1 Usage" and "P1 Generatie" in the same way without any issues. After a while (minutes) they all started having the red exclamation mark. Opening a device now tells me that it is currently unavailable. 

I checked the URL itself, but it is perfectly functional. Tried restarting the app, did not work. Adding another device at this moment tells me that there are no other devices available. 

Only after completely removing the ZTATZ app and reinstalling it again I could add the devices and they are functional for minutes again before getting the red exclamation mark again. 

**To Reproduce**
- Install the ZTATS application
- Add one or more devices
- Wait a couple of minutes

**Expected behavior**
I would have expected the application to keep working as it did the first couple of minutes. 

**Screenshots**
![err1](https://user-images.githubusercontent.com/34833303/142194487-1017f490-0fe3-4dff-b3f6-62edbbea49e8.png)
![err2](https://user-images.githubusercontent.com/34833303/142194508-e10ea2da-8f8c-4d40-ad7d-66c78c50c4df.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - Homey Version: Homey (Early 2018) version 7.1.6

**Comment by burnacid** [comment]
Can you please create a diagnostic report. You can find this in the ZTATZ app settings

**Comment by Cuflee** [comment]
Hmmm... I reinstalled the app, tried to add a device, typed my local URL just like before (http://p1mon.fritz.box) but now pressing "check" keeps indicating "Er zijn geen nieuwe apparaten gevonden" (no new devices found). Already tried a couple of times, where it could find the devices without any issues before it can't anymore so there is also no way for me to get them back in failed state again at the moment. I will try again tomorrow. The URL itself is working fine.

**Comment by burnacid** [comment]
Can you try connecting on IP instead of DNS name?

**Comment by Cuflee** [comment]
Weird..., that somehow seems to solve all of the issues. It could find the devices but I have them active without issues for a couple of hours now already. Thanks!

**Comment by burnacid** [comment]
Homey for some reason can't resolve the DNS name. That might have something to do with your network setup. I can't really change that in the app.
