### ISSUE TITLE
Usage values not correct in ztatz

### ISSUE THREAD

**Issue by wrutjes** [burnacid/homey-com.burnacid.ztatz#55]
Hello,

I've created an advanced flow on my Homey and then I don't see the values ​​I expect. I assume that "Final reading electricity use today" and "Final reading electricity production today" ("Eindstand electriciteit gebruik vandaag" em "Eindstand electriciteit productie vandaag" )  retrieve values ​​from p1 monitor at 0:00 and that the flow runs.

However, I see wrong values ​​in kWh consumption while the financial values ​​are good. Am I doing something wrong?

![ztatz-02b](https://github.com/burnacid/homey-com.burnacid.ztatz/assets/9075779/e2d39199-8af4-486e-ae53-515441435b31)
![ztatz-01](https://github.com/burnacid/homey-com.burnacid.ztatz/assets/9075779/c084e6df-3bf4-4cac-8607-6318ae87f204)
![ztatz-03](https://github.com/burnacid/homey-com.burnacid.ztatz/assets/9075779/eedbf04d-e31a-4a2a-a91a-e007f8be3c9e)

Thanks in advance.

Wilfried

**Comment by burnacid** [comment]
Are you using the tags that the if card (als) gives? or are those tags just the values from the device?
As the if card triggers after reset of Ztatz day value. It it then tags the last known value back in a tag.

This works fine for me 
<img width="330" alt="image" src="https://github.com/burnacid/homey-com.burnacid.ztatz/assets/852616/45f814da-cbb3-43b6-ac06-7ca1f68585e8">

<img width="687" alt="image" src="https://github.com/burnacid/homey-com.burnacid.ztatz/assets/852616/e3aa1589-15a5-4d86-b93e-66772bc3c2da">

**Comment by wrutjes** [comment]
Hello, thanks for your answer.

I am not sure how I did it but I made 2 new (simple) flows instead of one advanced flow and there was another tag that I could use which is not available in the advanced flow "Electriciteit geproduceerd".
So I now have the right values (that I want ) reported. 

It somehow doesn't work very consistently and not all tags are available in both flow options it seems.

![ztatz05](https://github.com/burnacid/homey-com.burnacid.ztatz/assets/9075779/9dbe049a-6301-4720-89e9-c3e140b9b73d)
![ztatz04](https://github.com/burnacid/homey-com.burnacid.ztatz/assets/9075779/43c27408-4aa4-481a-a3e5-fa5d55512e27)
![ztatz06](https://github.com/burnacid/homey-com.burnacid.ztatz/assets/9075779/ea572de2-0957-4860-8333-8ff10cb1e371)

Kind regards,

Wilfried

**Comment by burnacid** [comment]
Hi Wilfried

You want to use the values from This Flow:

<img width="390" alt="image" src="https://github.com/burnacid/homey-com.burnacid.ztatz/assets/852616/1fc2c132-16a3-47e5-bd8d-04df5d3db8f5">

Using values from the devices might render unexpected values. As they will be 0 at 0:00 
If you are missing values you rather have I could be able to make them. But for Eindstand electriciteit x vandaag it will only return the kWh value

**Comment by wrutjes** [comment]
For "Verbruik en opbrengst" I have used tags for this flow now and for the costs I have picked others from P1 Fiananciel Day. This is ok for me now. When I need more tags i'll let you know. Thanks for the offer and have a nice weekend.

![ztatz07](https://github.com/burnacid/homey-com.burnacid.ztatz/assets/9075779/9410192b-d729-47f4-83a8-d08801fee2d5)

kind regards, Wilfried
