### ISSUE TITLE
p1 daily usage not showing anything after update

### ISSUE THREAD

**Issue by Mike2873** [burnacid/homey-com.burnacid.ztatz#57]
After update it is not showing anything. Reinstalled app, reinstalled devices but nothing shows. Noticed that data didn’t refresh. After reinstalling device and app nothing shows anymore. 

P1 usage works normal

**Comment by burnacid** [comment]
Please see #56 
Duplicate issue will be closed

**Comment by Mike2873** [comment]
Beste,

Wat is nu verder de bedoeling dat ik de stappen uit #56 volg?

Mvg Mike

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Stefan Lenders ***@***.***>
Verzonden: Monday, October 30, 2023 2:59:40 PM
Aan: burnacid/homey-com.burnacid.ztatz ***@***.***>
CC: Mike2873 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [burnacid/homey-com.burnacid.ztatz] p1 daily usage not showing anything after update (Issue #57)


Please see #56<https://github.com/burnacid/homey-com.burnacid.ztatz/issues/56>
Duplicate issue will be closed

**Comment by burnacid** [comment]
Er staat een link in naar een test versie. Als je die kan installeren en laat weten of het voor je werkt. Dan weet ik of ik hem kan releasenThxVerzonden vanaf Outlook voor AndroidVan: Mike2873 ***@***.***>Verstuurd: maandag, oktober 30, 2023 3:04:51 p.m.Aan: burnacid/homey-com.burnacid.ztatz ***@***.***>CC: Stefan Lenders ***@***.***>; State change ***@***.***>Onderwerp: Re: [burnacid/homey-com.burnacid.ztatz] p1 daily usage not showing anything after update (Issue #57)
Beste,



Wat is nu verder de bedoeling dat ik de stappen uit #56 volg?



Mvg Mike



Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>

________________________________

Van: Stefan Lenders ***@***.***>

Verzonden: Monday, October 30, 2023 2:59:40 PM

Aan: burnacid/homey-com.burnacid.ztatz ***@***.***>

CC: Mike2873 ***@***.***>; Author ***@***.***>

Onderwerp: Re: [burnacid/homey-com.burnacid.ztatz] p1 daily usage not showing anything after update (Issue #57)





Please see #56<https://github.com/burnacid/homey-com.burnacid.ztatz/issues/56>

Duplicate issue will be closed

**Comment by Mike2873** [comment]
Die heb ik geïnstalleerd maar dan krijg ik een foutmelding op een watermeter die ik niet heb

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Stefan Lenders ***@***.***>
Verzonden: Monday, October 30, 2023 3:24:29 PM
Aan: burnacid/homey-com.burnacid.ztatz ***@***.***>
CC: Mike2873 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [burnacid/homey-com.burnacid.ztatz] p1 daily usage not showing anything after update (Issue #57)


Er staat een link in naar een test versie. Als je die kan installeren en laat weten of het voor je werkt. Dan weet ik of ik hem kan releasenThxVerzonden vanaf Outlook voor AndroidVan: Mike2873 ***@***.***>Verstuurd: maandag, oktober 30, 2023 3:04:51 p.m.Aan: burnacid/homey-com.burnacid.ztatz ***@***.***>CC: Stefan Lenders ***@***.***>; State change ***@***.***>Onderwerp: Re: [burnacid/homey-com.burnacid.ztatz] p1 daily usage not showing anything after update (Issue #57)
Beste,



Wat is nu verder de bedoeling dat ik de stappen uit #56 volg?



Mvg Mike



Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>

________________________________

Van: Stefan Lenders ***@***.***>

Verzonden: Monday, October 30, 2023 2:59:40 PM

Aan: burnacid/homey-com.burnacid.ztatz ***@***.***>

CC: Mike2873 ***@***.***>; Author ***@***.***>

Onderwerp: Re: [burnacid/homey-com.burnacid.ztatz] p1 daily usage not showing anything after update (Issue #57)





Please see #56<https://github.com/burnacid/homey-com.burnacid.ztatz/issues/56>

Duplicate issue will be closed
