### ISSUE TITLE
Info to homey

### ISSUE THREAD

**Issue by rpb006** [burnacid/homey-com.burnacid.ztatz#65]
The info to homey is only when I restart the app. And then only once until I restart the app ztatz again.
Can this be solved?

**Comment by burnacid** [comment]
Probably, but I need more info and time.
Next 2 weeks I can't fix it if it's an issue with the app.

Can you please go in the settings of the app and submit a diagnostic report for me. Thanks

**Comment by rpb006** [comment]
a0c7cd01-3f66-4677-95b2-967bb1d52dc8

Report info

I can make another report tomorrow when info is old in homey again.

Op ma 5 feb. 2024 22:06 schreef Stefan Lenders ***@***.***>:

**Comment by burnacid** [comment]
Please restart the app then wait 5 minutes before submitting a report.

**Comment by burnacid** [comment]
Can you switch on debug of one of the devices (settings of the device) let it run for 3 minutes and submit a report after. 

Don't restart the app after you switched on debugging

**Comment by rpb006** [comment]
Hi. Debug is at least 3 minutes activated.

f3eb9666-59b2-45ef-b743-b84f0a9038b4

Report make just before i closed debug.

Op ma 5 feb. 2024 23:02 schreef Stefan Lenders ***@***.***>:

**Comment by burnacid** [comment]
Error: connect ETIMEDOUT 192.168.3.41:80 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -110, code: 'ETIMEDOUT', syscall: 'connect', address: '192.168.3.41', port: 80 } 

It simply can't connect. It gets a connection timeout . Please check your network connectivity.

**Comment by rpb006** [comment]
The network connection is ok.
I can connect to the homey, to the p1mon pi and after a restart of the
ztatz app it connects.
But when i opened a ztatz device on homey I got an orange bar with the text
"Refresh seems to take long..."




Op di 6 feb. 2024 10:55 schreef Stefan Lenders ***@***.***>:

**Comment by burnacid** [comment]
Homey tries to connect to

http://192.168.3.41/api/v1/smartmeter?limit=1

That times out. What is why you are getting the orange bar. Not something I can fix in the app.

Please check if you can reach it and check if any firewalls block that traffic.

Has it worked before?

**Comment by rpb006** [comment]
It worked perfect . It started last two weeks.
No further problems on network.

Op di 6 feb. 2024 11:15 schreef Stefan Lenders ***@***.***>:

**Comment by rpb006** [comment]
Maybe it started after the last update 0.8.6

Op di 6 feb. 2024 12:01 schreef rpb006 ***@***.***>:

**Comment by burnacid** [comment]
The app didn't change nor was ztatz. So if it work there is no factor from the app side that could have broken it.

The error you are getting again is network related.
You can try removing one of the devices and re-adding them. Further help I can offer in 2 weeks. But then I would need to troubleshoot within your network.

**Comment by rpb006** [comment]
I shall duplicate an ztatz app on homey. See if the new one connect better.
Thanks for your suggestions so far.

Op di 6 feb. 2024 12:29 schreef Stefan Lenders ***@***.***>:

**Comment by burnacid** [comment]
Might have been an issue with the homey version for some reason.
As it works again I'll close the case
