### ISSUE TITLE
Niet de juiste fases waarden in homey

### ISSUE THREAD

**Issue by basnahuis** [burnacid/homey-com.burnacid.ztatz#70]
De waardes van de fasen worden niet weergegeven in Homey. 
Terwijl in de P1 app op de telefoon wel alles volledig word weergegeven gebeurd dat niet in Homey. 
Wel worden de voltages juist weergegeven. 

Ook werken de rest van de functies voor mij zover ik ze gebruik, zoals P1 generatie en P1 verbruik. 
Zie hieronder schermafbeelding van Homey.
![Schermafbeelding 2024-06-19 131622](https://github.com/burnacid/homey-com.burnacid.ztatz/assets/46353735/4de2084a-c47b-44c4-beac-83c1fadfb0a6)

Hieronder de schermafbeelding van P1 app. 
![Afbeelding van WhatsApp op 2024-06-19 om 13 25 25_f8a25a8b](https://github.com/burnacid/homey-com.burnacid.ztatz/assets/46353735/22ad470d-b056-43d1-acfa-b4e85e5fd789)

doe ik wat fout of kan ik het verhelpen?

**Comment by burnacid** [comment]
Versie ztatz en Homey app?

**Comment by basnahuis** [comment]
> Versie ztatz en Homey app?

Versies:
P1 monitor: (raspberry pi) 2.4.1
Homey(2019)  versie: 10.0.10
ZTATZ (op homey): 0.8.8

**Comment by burnacid** [comment]
Lijkt nogal op #66 welke al opgelost moet zijn.

Kan je me de output aanleveren van de api http://yourztatzurl/api/v1/status?json=object

Vervang hier de url

**Comment by basnahuis** [comment]
Kan ik dan nog ergens wat updaten?
zag die post en ben wel recent overgestapt van 1 fase naar 3 fasen aansluiting, met nieuwe meter. (kan dit het probleem zijn?)
De rest van de de informatie werkt allemaal wel, had het dus nog niet direct in de meter gezocht. 

Zie hierbij de files. 
[status.json](https://github.com/user-attachments/files/15901328/status.json)
[status (1).json](https://github.com/user-attachments/files/15901339/status.1.json)

**Comment by burnacid** [comment]
Is dat diagnose rapport vanuit de ZTATZ app? want die heb ik helaas niet ontvangen.

Zou je eens het volgende kunnen doen
De Phases device settings aanpassen een Debug aanzetten
Vervolgens 5 minuten wachten. En vervolgens in de ZTATZ app binnen homey een diagnostic report maken.

**Comment by basnahuis** [comment]
Zojuist weer een gemaakt. Komt die nu wel over?
Ik doe dit in de app Ztatz in de Homey app.

Code: b43fe3f1-6bf0-4c72-80f9-7b0761ec590d

![IMG_5490](https://github.com/burnacid/homey-com.burnacid.ztatz/assets/46353735/5eb085f8-a302-461a-84cc-262bf542f9f6)

**Comment by burnacid** [comment]
Ik krijg van jou gewoon geen rapport.binnen. zelf effe getest daar werkt het zonder issues. Heb je de app / homey al eens herstart?

**Comment by basnahuis** [comment]
zojuist weer een gemaakt, app en homey meerdere keren opnieuw opgestart.

**Comment by burnacid** [comment]
ik heb nu wel een diagnostic report ontvangen. Maar het device staat niet op debug (hij gaat automatisch van debug af bij een reboot).
Kan je deze op debug zetten en na 5 minuten er nog een diagnostic rapport van versturen?

**Comment by basnahuis** [comment]
Excuses, daar had ik niet aandacht.
Nu weer een gestuurd: d78c519c-257d-4450-a164-170fcdbe8ac0

**Comment by burnacid** [comment]
Ik weet niet waar dit fout loopt... Ik ontvang het rapport gewoon niet...
Dus kan niet achterhalen waar dit mist loopt helaas op deze manier.

**Comment by basnahuis** [comment]
Dat is vreemd, heb even opnieuw toegevoegd maar dit helpt niet.
Wederom weer een rapport geprobeerd te versturen: be0dfa53-d4c0-471e-9c35-f89e65121e50

**Comment by burnacid** [comment]
Dat zou zo maar een oorzaak kunnen zijn. Ik ga het bekijken

**Comment by burnacid** [comment]
> Lijkt nogal op #66 welke al opgelost moet zijn.
> 
> Kan je me de output aanleveren van de api http://yourztatzurl/api/v1/status?json=object
> 
> Vervang hier de url

Kan je dit nog een keer aanleveren op het moment dat je teruglevert?

**Comment by basnahuis** [comment]
Hierbij alvast de api output zonder terug levering. 
[status (3).json](https://github.com/user-attachments/files/16433083/status.3.json)
[status (2).json](https://github.com/user-attachments/files/16433084/status.2.json)

zal morgen die maken van met terug levering.

**Comment by basnahuis** [comment]
Nu met terug levering. 
[status (5).json](https://github.com/user-attachments/files/16437150/status.5.json)
[status (4).json](https://github.com/user-attachments/files/16437152/status.4.json)

**Comment by burnacid** [comment]
Dit verklaart veel. De levering KW zit in een andere value.

```
    {
        "LABEL": "Huidige KW verbruik L1 (21.7.0)",
        "SECURITY": 0,
        "STATUS": "0.0",
        "STATUS_ID": 74
    },
    {
        "LABEL": "Huidige KW verbruik L2 (41.7.0)",
        "SECURITY": 0,
        "STATUS": "0.437",
        "STATUS_ID": 75
    },
    {
        "LABEL": "Huidige KW verbruik L3 (61.7.0)",
        "SECURITY": 0,
        "STATUS": "0.002",
        "STATUS_ID": 76
    },
    {
        "LABEL": "Huidige KW levering L1 (22.7.0)",
        "SECURITY": 0,
        "STATUS": "0.0",
        "STATUS_ID": 77
    },
    {
        "LABEL": "Huidige KW levering L2 (42.7.0)",
        "SECURITY": 0,
        "STATUS": "0.0",
        "STATUS_ID": 78
    },
    {
        "LABEL": "Huidige KW levering L3 (62.7.0)",
        "SECURITY": 0,
        "STATUS": "0.0",
        "STATUS_ID": 79
    },
```


```
    {
        "LABEL": "Huidige KW verbruik L1 (21.7.0)",
        "SECURITY": 0,
        "STATUS": "0.0",
        "STATUS_ID": 74
    },
    {
        "LABEL": "Huidige KW verbruik L2 (41.7.0)",
        "SECURITY": 0,
        "STATUS": "0.0",
        "STATUS_ID": 75
    },
    {
        "LABEL": "Huidige KW verbruik L3 (61.7.0)",
        "SECURITY": 0,
        "STATUS": "0.0",
        "STATUS_ID": 76
    },
    {
        "LABEL": "Huidige KW levering L1 (22.7.0)",
        "SECURITY": 0,
        "STATUS": "0.0",
        "STATUS_ID": 77
    },
    {
        "LABEL": "Huidige KW levering L2 (42.7.0)",
        "SECURITY": 0,
        "STATUS": "0.458",
        "STATUS_ID": 78
    },
    {
        "LABEL": "Huidige KW levering L3 (62.7.0)",
        "SECURITY": 0,
        "STATUS": "0.739",
        "STATUS_ID": 79
    },
```

**Comment by burnacid** [comment]
@basnahuis kan je deze test versie eens installleren aub: https://homey.app/a/com.burnacid.ztatz/test/

**Comment by basnahuis** [comment]
Dat verklaard een hoop dan.
De test versie geïnstalleerd maar nu werkt er niks meer. Zie screen shots hieronder. 
![IMG_6056](https://github.com/user-attachments/assets/944a61ad-3ec1-4de5-9afd-64118ba89c62)
![IMG_6057](https://github.com/user-attachments/assets/7c6feaaa-96ea-468a-ba27-6a87faf54beb)

**Comment by burnacid** [comment]
Dit is heel gek, als ik de app installeer vanuit mijn ontwikkelomgeving is er niets aan de hand. Zo dra ik de app package en installeer via de Homey Store is die broken... Ik denk dat ik helaas daar voor contact moet gaan zoeken met Athom.

Kijk even of je de originele versie terug kan installeren aub.

**Comment by basnahuis** [comment]
Dat is vreemd, hopelijk kom je er verder mee met Anthom.

Ben weer terug gegaan naar de vorige versie en die werkt weer.

**Comment by burnacid** [comment]
Ik ben niet de enige zo te zien op de developers slack

<img width="500" alt="image" src="https://github.com/user-attachments/assets/3a1d6994-ae77-4321-beae-3a18b773b070">

**Comment by basnahuis** [comment]
Klopt nu werkt het, de juiste waardes worden nu ook weergegeven met terug leveren. Zal vanavond even kijken of het zonder ook nog werkt maar ga ik wel vanuit.

**Comment by basnahuis** [comment]
Zag alleen dat de amperes niet worden weergegeven. Heeft dat er ook mee te maken?

zie scherm afbeelding 
![IMG_6063](https://github.com/user-attachments/assets/c12880c2-c6eb-4523-a676-33408c12ecd7)

**Comment by burnacid** [comment]
L1 moet hier 0 zijn
L3 is raar. Daar moet ik naar kijken. Wellicht heb je meer aan calculated amperage (zie de settings in het phases device)
ZTATZ geeft je amperage die is afgerond. Ik heb een toggable setting gemaakt om aperage op basis van een berekening te doen
